name: CI Pipeline
on:
    push:
        branch:
            - master
    pull_request:
        branch:
            - master
jobs:
    test:
        run-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install Node
              uses: actions/setup-node@v2
              with:
                node-version: '22'
            - name: Install dependencies
              uses: npm install
            - name: Run tests
              uses: npm test

            
                
